
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waqeierxlkallppzensg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhcWVpZXJ4bGthbGxwcHplbnNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzE0OTEsImV4cCI6MjA2MDEwNzQ5MX0.AgO_fe42rfbaCfqpppGZMUYwyhRKFwYi8APESp1qJQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
